// <auto-generated />
using System;
using Ballware.Ml.Data.Ef.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ballware.Ml.Data.Ef.Postgres.Migrations
{
    [DbContext(typeof(MlDbContext))]
    partial class MlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ballware.Ml.Data.Persistables.MlModel", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreateStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_stamp");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Identifier")
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<DateTime?>("LastChangeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_change_stamp");

                    b.Property<Guid?>("LastChangerId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_changer_id");

                    b.Property<string>("Options")
                        .HasColumnType("text")
                        .HasColumnName("options");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TrainResult")
                        .HasColumnType("text")
                        .HasColumnName("train_result");

                    b.Property<string>("TrainSql")
                        .HasColumnType("text")
                        .HasColumnName("train_sql");

                    b.Property<int>("TrainState")
                        .HasColumnType("integer")
                        .HasColumnName("train_state");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("pk_ml_model");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_ml_model_tenant_id");

                    b.HasIndex("TenantId", "Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_ml_model_tenant_id_identifier");

                    b.HasIndex("TenantId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_ml_model_tenant_id_uuid");

                    b.ToTable("ml_model", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
