// <auto-generated />
using System;
using Ballware.Ml.Data.Ef.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ballware.Ml.Data.Ef.SqlServer.Migrations
{
    [DbContext(typeof(MlDbContext))]
    [Migration("20250825060015_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ballware.Ml.Data.Persistables.MlModel", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreateStamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_stamp");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("creator_id");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("identifier");

                    b.Property<DateTime?>("LastChangeStamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_change_stamp");

                    b.Property<Guid?>("LastChangerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_changer_id");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("options");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TrainResult")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("train_result");

                    b.Property<string>("TrainSql")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("train_sql");

                    b.Property<int>("TrainState")
                        .HasColumnType("int")
                        .HasColumnName("train_state");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("pk_ml_model");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_ml_model_tenant_id");

                    b.HasIndex("TenantId", "Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_ml_model_tenant_id_identifier")
                        .HasFilter("[identifier] IS NOT NULL");

                    b.HasIndex("TenantId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_ml_model_tenant_id_uuid");

                    b.ToTable("ml_model", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
